name: deploy

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0.2'
        bundler-cache: true
    - name: Install deps
      run: |
        npm install -g mermaid.cli
    - name: Build site
      run: |
        export JEKYLL_ENV=production
        bundle exec jekyll build
    - name: Deploy to GitHub Pages
      if: github.event_name != 'pull_request'
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        
        # Create and switch to gh-pages branch
        git checkout --orphan gh-pages
        
        # Remove everything except _site directory
        find . -maxdepth 1 ! -name '_site' ! -name '.git' -exec rm -rf {} \;
        
        # Move _site contents to root
        mv _site/* .
        rm -rf _site
        
        # Create .nojekyll file
        touch .nojekyll
        
        # Add, commit and push changes
        git add -A
        git commit -m "Deploy to GitHub Pages"
        git push -f origin gh-pages
